Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2021-12, with the labels that each got.

#7 Prevent hpa from scaling deployments when cluster is hibernated
  pkg/controller/lifecycle/actuator.go
Labels: area/auto-scaling, reviewed/lgtm, needs/ok-to-test, size/xs

#8 Enhance component descriptor calculation
  .ci/component_descriptor
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#10 Add documentation and docforge manifest file
  .docforge/manifest.yaml
  docs/installation/installation.md
  docs/usage/openidconnects.md
Labels: area/documentation, area/usability, reviewed/lgtm, needs/ok-to-test, size/m

#11 Add check for docforge manifest files
  Makefile
  hack/check-docforge.sh
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#13 Update golang to 1.16.11 and alpine to 3.13.7
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#12 Add priorityclass, pdb and node antiaffinity for the extension deployment
  charts/gardener-extension-shoot-oidc-service/templates/deployment.yaml
  charts/gardener-extension-shoot-oidc-service/templates/poddisruptionbudget.yaml
  charts/gardener-extension-shoot-oidc-service/templates/priorityclass.yaml
  charts/gardener-extension-shoot-oidc-service/templates/vpa.yaml
  charts/gardener-extension-shoot-oidc-service/values.yaml
  example/controller-registration.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#14 Do not automount service account tokens for the OWA pods
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
