Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2022-08, with the labels that each got.

#54 Remove go templates from manifest
  .docforge/manifest.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#53 Remove install-requirements recipe
  Makefile
Labels: kind/cleanup, reviewed/lgtm, needs/ok-to-test, size/xs

#56 Added linters to make check
  .golangci.yaml
  Makefile
  pkg/apis/config/v1alpha1/defaults.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/cmd/options.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  pkg/webhook/kapiserver/webhook.go
  test/system/lifecycle/lifecycle_test.go
Labels: needs/ok-to-test, needs/changes, size/s

#58 Increase cpu limits
  charts/gardener-extension-shoot-oidc-service/values.yaml
  example/controller-registration.yaml
  pkg/controller/lifecycle/actuator.go
Labels: area/robustness, needs/ok-to-test, needs/rebase, needs/review, size/xs
