Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2023-10, with the labels that each got.

#126 Remove unused clientset
  pkg/controller/lifecycle/actuator.go
  pkg/controller/lifecycle/add.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#127 Enable the extension for workerless shoots
  charts/gardener-extension-shoot-oidc-service/doc.go
  example/controller-registration.yaml
  example/local/01-shoot-workerless.yaml
  example/local/01-shoot.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#128 update go to version 1.21.2
  .test-defs/lifecycle.yaml
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#129 Move pkg/imagevector to imagevector
  .ci/set_dependency_version
  .dockerignore
  charts/images.go
  imagevector/images.yaml
  imagevector/imagevector.go
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#131 Update golang to 1.21.3
  .test-defs/lifecycle.yaml
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#135 Add requiredClaims to usage docs
  docs/usage/openidconnects.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#136 Update openidconnect CRD
  pkg/controller/lifecycle/templates/authentication.gardener.cloud_openidconnects.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#120 Introduce the use of central manifest
  .docforge/manifest.yaml
  Makefile
Labels: area/documentation, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/s
