Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2023-01, with the labels that each got.

#80 Drop support for kubernetes < 1.20 for shoot oidc service extension
  example/10-fake-shoot-controlplane.yaml
  example/30-cluster.yaml
  hack/api-reference/config.json
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#81 Build multi-arch images for amd64 and arm64
  .ci/pipeline_definitions
  Dockerfile
  Makefile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#82 Bump golang to 1.19.5
  .test-defs/lifecycle.yaml
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#75 Adapt high-availability configuration
  README.md
  charts/gardener-extension-shoot-oidc-service/templates/deployment.yaml
  charts/gardener-extension-shoot-oidc-service/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
  pkg/controller/lifecycle/actuator.go
  test/system/lifecycle/lifecycle_test.go
Labels: area/high-availability, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/m

#84 Use constant for ha config type label
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
