Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2023-03, with the labels that each got.

#94 Remove minAllowed.cpu for all components
  charts/gardener-extension-shoot-oidc-service/templates/vpa.yaml
  charts/gardener-extension-shoot-oidc-service/values.yaml
  example/controller-registration.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#97 Wait oidc deployment rollout
  charts/gardener-extension-shoot-oidc-service/templates/rbac.yaml
  example/controller-registration.yaml
  hack/test-e2e-provider-local.sh
  pkg/controller/lifecycle/actuator.go
  pkg/controller/lifecycle/add.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#98 Update go version to 1.20.2
  .test-defs/lifecycle.yaml
  Dockerfile
  go.mod
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#99 Allow OWA to istio-ingressgateway
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#100 Remove unused controller options
  cmd/gardener-extension-shoot-oidc-service/app/app.go
  cmd/gardener-extension-shoot-oidc-service/app/options.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#101 Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#103 Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove` (#101)
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#105 Scrape OWA
  Makefile
  hack/oidc-up.sh
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s
