Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2024-01, with the labels that each got.

#140 switch GCR -> Artifact-Registry
  .ci/component_descriptor
  .ci/pipeline_definitions
  Makefile
  charts/gardener-extension-shoot-oidc-service/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, needs/ok-to-test, size/s

#145 Add dependabot definition
  .github/dependabot.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#147 Add apiVersion to test definition
  .test-defs/lifecycle.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
