Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2025-04, with the labels that each got.

#303 Switch Slack references to Gardener workspace
  README.md
Labels: area/open-source, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs

#302 Address TODO for legacy NetworkPolicy labels
  charts/gardener-extension-shoot-oidc-service/templates/service.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#306 Improve usage documentation
  docs/usage/openidconnects.md
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#298 Remove RBAC wildcard references
  charts/gardener-extension-shoot-oidc-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#309 Update golang.org/x/crypto to v0.35.0
  go.mod
  go.sum
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/s

#308 Remove extension configmap permissions
  charts/gardener-extension-shoot-oidc-service/templates/rbac.yaml
  cmd/gardener-extension-shoot-oidc-service/app/app.go
  example/25-rbac.yaml
  example/controller-registration.yaml
  example/local/01-shoot-workerless.yaml
  example/local/01-shoot.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#311 Enhance KubeAPIServer ensurer to use container Args instead of Command
  pkg/webhook/kapiserver/ensurer.go
  pkg/webhook/kapiserver/mutator_test.go
  test/e2e/create_enable_disrupt_reconcile_delete_test.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/s

#313 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-shoot-oidc-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/quality, kind/regression, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
