Repository gardener/gardener-extension-shoot-oidc-service, pull requests merged in 2025-08, with the labels that each got.

#343 Convert reuse configs to dep5
  .github/workflows/reuse-check.yaml
  .reuse/dep5
  REUSE.toml
Labels: needs/review, size/s

#342 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: needs/review, size/s

#350 Add build and go report card badges
  README.md
Labels: area/delivery, kind/cleanup, reviewed/lgtm, size/xs

#351 Various improvements of GHA used to build repo
  .ci/hack/component_descriptor
  .ci/hack/doc.go
  .ci/hack/generate-controller-registration.sh
  .ci/hack/prepare_release
  .ci/hack/set_dependency_version
  .ci/prepare_release
  .ci/set_dependency_version
  .ci/verify
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  Makefile
  hack/tools.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xl
